baseURL = "http://example.org/"
languageCode = "en-us"
title = "DroidBook"

theme = "good-to-go"

paginate = 4

[params]
    description = "My site description"
    author = "buttdev.kr"
    authorImage = "/images/buttdev.jpg"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Categories"
    url = "/categories"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/nofailed"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Contact"
  url = "/contact"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

#[[menu.footer]]
#  name = "Privacy"
#  url = "/privacy"
