baseURL = "https://buttdev.github.io/"
languageCode = "en-us"
title = "ButtDev"

theme = "good-to-go"
#theme = "hugo-PaperMod"

paginate = 4

[params]
    description = "My site description"
    author = "buttdev.kr"
    authorImage = "/images/buttdev.jpg"

[taxonomies]
    category = 'categories'
    series = 'series'
    tag = 'tags'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "Search"
    url = "/search"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Categories"
    url = "/categories"

[[menu.main]]
    name = "Tags"
    url = "/tags"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/buttdev"
    pre = "<i class='fab fa-github'></i>"

#[[menu.social]]
#    name = "YouTube"
#    url = "https://www.youtube.com/channel/"
#    pre = "<i class='fab fa-youtube'></i>"

#[[menu.social]]
#    name = "Twitter"
#    url = "https://twitter.com/buttdev
#    pre = "<i class='fab fa-twitter'></i>"

# menu.main replaces by footer
#[[menu.footer]]
#  name = "Contact"
#  url = "/contact"

#[[menu.footer]]
#  name = "Privacy"
#  url = "/privacy"

# This allows content can use html grammar in it.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params.plantuml]
    enable = true
    theme = "default"
    #Set url to plantuml server
    #default is http://www.plantuml.com/plantuml/svg/
    server = "https://www.plantuml.com/plantuml/svg/"


[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

[permalinks]
    blog = "/blog/:filename/"
