baseURL = "https://buttdev.github.io/"
languageCode = "en-us"
title = "ButtDev"

theme = "good-to-go"

paginate = 4

[params]
    description = "My site description"
    author = "buttdev.kr"
    authorImage = "images/buttdev.jpg"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Categories"
    url = "/categories"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/nofailed"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Contact"
  url = "/contact"

#[[menu.footer]]
#  name = "Privacy"
#  url = "/privacy"

# This allows content can use html grammar in it.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
